version: "3.8"

services:
  ccx:
    build:
      context: .
      target: prod
      dockerfile: ./packages/ccx/docker/linux/Dockerfile
      args:
          URL_BASE: $URL_BASE
    tty: true
    volumes:
      - ./.docker/ccx_logs:/ccx_logs
      - ./.docker/ccx-store:/ccx-store
      - ./packages/plugins:/ccx-store/plugins/global
    restart: always
    env_file:
      - .env
    environment:
      - CONTROLLER_HOST
      - API_PORT
      - GIT_PORT
      - SESSION_SECRET
      - SESSION_DB_URI
      - DB_URI
      - WORKERS
    ports:
      - "$CLIENT_PORT:80" 
      - "$API_PORT:80"
      - "$GIT_PORT:5000"
    depends_on:
      - mongo
      - worker

  worker:
    build:
      context: packages/worker
      dockerfile: docker/linux/Dockerfile
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./.docker/mongo_data:/data/db